services:
  - docker
jobs:
  include:
    - stage: build docker image
      script:
      - docker build --target test  --tag todo-app:test .
    - stage: Run Tests
      script: docker run --env-file ./.env.test todo-app:test tests
    - script: docker run --env-file ./.env todo-app:test tests_e2e