language: bash
sudo: required
service:
- docker
jobs:
  include:
    - stage: build and test
      script:
      - docker build --target test  --tag todo-app-test:latest .
      - docker run --env-file .env.test --entrypoint poetry
        todo-app-test:latest run pytest tests
      - docker run -e MONGO_CONNECTION_STRING -e MONGO_DB_NAME -e SECRET_KEY -e GITHUB_CLIENT_ID -e GITHUB_CLIENT_SECRET --entrypoint poetry
        todo-app-test:latest run pytest tests_e2e


before_deploy:
- docker build --target production --tag $DOCKER_USERNAME/todo-app-prod:latest .
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push $DOCKER_USERNAME/todo-app-prod:latest

deploy:
  provider: script
  script: bash ./webhook.sh
  on:
    branch: module-10

after_success:
- echo "All done!"

notifications:
  email:
    recipients:
      - kiranuppi@gmail.com
    on_success: always
    on_failure: always
  slack: corndeldevops-jul3809:vz4EBKT04B7AidKS3MCzAVBs