language: bash
sudo: required
service:
- docker
- docker-compose
jobs:
  include:
    - stage: build and test
      script:
      - docker-compose -f docker-compose-dev.yml up -d --build
      - docker run --env-file .env.test --entrypoint poetry
        todo-app-test:latest run pytest tests
      - docker run -e MONGO_CONNECTION_STRING -e MONGODB_COLLECTION_NAME -e SECRET_KEY --entrypoint poetry
        todo-app-test:latest run pytest tests_e2e


before_deploy:
- docker build --target production --tag $dockerUsername/todo-app-prod:latest .
- echo "$dockerPassword" | docker login -u "$dockerUsername" --password-stdin
- docker push $dockerUsername/todo-app-prod:latest

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master

after_success:
- echo "All done!"

notifications:
  email:
    recipients:
      - kiranuppi@gmail.com
    on_success: always
    on_failure: always
  slack: corndeldevops-jul3809:vz4EBKT04B7AidKS3MCzAVBs