language: python
services:
  - docker
jobs:
  include:
    - stage: build and test
      script:
      - docker build --target test  --tag todo-app:test .
      - docker run --env-file ./.env.test todo-app:test tests
      - docker run --env-file ./.env.test todo-app:test tests_e2e
