language: python
services:
- docker
jobs:
  include:
  - stage: build and test
    script:
    - docker build --target test  --tag todo-app:test .
    - docker run -e SECRET_KEY -e API_KEY -e API_TOKEN todo-app:test tests_e2e
    - docker run --env-file ./.env.test todo-app:test tests

  - stage: docker build and publish
    script:
    - docker build --target production --tag $DOCKER_USERNAME/todo-app:prod .
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push $DOCKER_USERNAME/todo-app:prod

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: module-8
#  - stage: Deployment to Heroku
#    script:
#    - docker pull $DOCKER_USERNAME/todo-app:prod
#    - docker tag $DOCKER_USERNAME/todo-app:prod registry.heroku.com/ku-todo-app/web
#    - echo "$HEROKU_API_KEY" | docker login --username="$HEROKU_USERNAME" --password-stdin registry.heroku.com
#    - docker push registry.heroku.com/ku-todo-app/web
#    - heroku container:login
#    - heroku container:release web --app ku-todo-app
notifications:
  email:
    recipients:
      - kiranuppi@gmail.com
    on_success: always
    on_failure: always
  slack: corndeldevops-jul3809:vz4EBKT04B7AidKS3MCzAVBs